name: Github Actions Tests

on:
  workflow_call:
  pull_request:

permissions:
  contents: read

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Detect secrets
        uses: govuk-pay/pay-ci/actions/detect-secrets@8597f9957716cb928c22ed66ee0704a24798ce6e

  tests:
    name: Docker build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build dockerfile (includes executing tests)
        run: |
          set -euo pipefail

          # Note: The docker build includes executing the tests as part of the build
          docker build -t test .
